### ISSUE TITLE
This picture not working demo webpage.

### ISSUE THREAD

**Issue by Seajelly** [google/brunsli#31] opened 2019-08-25 04:45 UTC
[https://alapblog.hu/wp-content/uploads/2019/08/regio-07-002.jpg](https://alapblog.hu/wp-content/uploads/2019/08/regio-07-002.jpg)

Message only : 
Processing alapblog_regio-07-002.jpg as JPEG
Input size: 4354115

No .jxl output.

**Comment by eustas** [comment] 2019-08-25 09:50
Duplicate of #30

**Closed by eustas** 2019-08-25 09:50 UTC
